const loadingMessages = [
    "Engaging quasar splitter",
    "Activating nebula siphon",
    "Calibrating wormhole compass",
    "Initializing dimension shifter",
    "Aligning gravity inverter",
    "Forming stasis bubble",
    "Starting time loop engine",
    "Charging antigrav boots",
    "Securing cosmic anchor",
    "Crafting molecular disruptor",
    "Energizing chrono-blade",
    "Heating stellar forge",
    "Mapping galactic ley lines",
    "Tuning void resonator",
    "Boosting psi-amplifier",
    "Connecting neural nexus",
    "Powering up plasma gauntlet",
    "Generating rift stabilizer",
    "Activating singularity coil",
    "Deploying dimensional anchor",
    "Calibrating etheric transponder",
    "Linking quantum entangler",
    "Deploying chrono-shield",
    "Aligning warp stabilizer",
    "Starting infinity drive",
    "Spinning vortex manipulator",
    "Broadcasting subspace transmitter",
    "Calibrating tachyon inverter",
    "Preparing null field generator",
    "Activating chrono key",
    "Starting ether drive",
    "Firing vortex cannon",
    "Harvesting solar energy",
    "Initializing chaos matrix",
    "Navigating stellar map",
    "Sharpening void blade",
    "Charging neutron lance",
    "Sequencing spacetime",
    "Locking quantum cipher",
    "Disrupting phase field",
    "Projecting astral form",
    "Inverting entropy flow",
    "Anchoring reality",
    "Prisming stellar light",
    "Forging nebula",
    "Decrypting quantum cipher",
    "Charging void capacitor",
    "Incubating alien spider eggs",
    "Harnessing vortigaunt energy",
    "Crystallizing light saber crystals",
    "Deciphering scroll of doom",
    "Charging quantum flux capacitor",
    "Mobilizing zombie horde",
    "Translating ancient runes",
    "Opening mystic portal",
    "Resolving time-travel paradox",
    "Charging photon blaster",
    "Creating gravity well",
    "Calculating wormhole coordinates",
    "Charting celestial map",
    "Casting arcane spells",
    "Engaging stealth module",
    "Generating dark matter",
    "Activating cryo-chamber",
    "Simulating holo-deck",
    "Deploying plasma shield",
    "Starting fusion reactor",
    "Installing cybernetic implants",
    "Extracting alien DNA",
    "Charging warp drive",
    "Activating cloaking device",
    "Harnessing void energy",
    "Linking teleportation grid",
    "Opening dimension rift",
    "Decrypting nuclear launch codes",
    "Computing telekinetic algorithms",
    "Charging psi-blade",
    "Harvesting nebula dust",
    "Generating shield",
    "Activating interstellar beacon",
    "Upgrading exosuit",
    "Deploying nanobot swarm",
    "Firing antimatter cannon",
    "Activating cryogenic stasis",
    "Preparing solar flares",
    "Commanding galactic empire",
    "Firing orbital lasers",
    "Tapping tesseract energy",
    "Synchronizing AI consciousness",
    "Detecting paranormal activity",
    "Stabilizing space-time continuum",
    "Interpreting ancient prophecy",
    "Reinforcing digital firewall",
    "Containing viral outbreak",
    "Suppressing robotic uprising",
    "Activating cloning facility",
    "Engaging invisibility cloak",
    "Calculating chaos theory",
    "Monitoring supernova explosion",
    "Deploying combat drones",
    "Charging plasma rifle",
    "Activating planetary defense system",
    "Analyzing alien artifact",
    "Investigating black hole anomaly",
    "Initializing holographic interface",
    "Entangling quantum particles"
]
// .filter(x => x.length < 24 & x.length > 16)
.map(x => x.toLowerCase())
let idx = 0
const getMessage = () => {
    idx = (idx + 1) % loadingMessages.length
    return loadingMessages[idx]
}

export default getMessage